# Generated by Django 2.0.3 on 2018-04-04 02:20

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='emailT',
        ),
        migrations.RemoveField(
            model_name='users',
            name='usernameT',
        ),
        migrations.AddField(
            model_name='users',
            name='a',
            field=models.CharField(default=1, max_length=50, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='b',
            field=models.EmailField(default=1, max_length=150, validators=[django.core.validators.EmailValidator()]),
            preserve_default=False,
        ),
    ]
