# Generated by Django 2.0.3 on 2018-04-04 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180404_0220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='b',
            new_name='email_field',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='a',
            new_name='username_field',
        ),
    ]
